---

- name: Install httpd24
  hosts: all
  become: yes

  tasks:

  - name: Check if the package is present in current Repo
    shell: yum list available | grep -i httpd24-httpd
    register: package_check
    failed_when: no
    changed_when: no

  - name: Install yum repository for the RedHat Sowtware collection for RedHat 6.X
    yum_repository:
      name: scl-el-6
      description: Software Collections for Enterprise Linux 6 - x86_64
      baseurl: http://yum.os.amadeus.net/mirror/latest/rhel-server-rhscl-6-rpms/
      file: scl_repo
      enabled: yes
      gpgcheck: no
    when: package_check.rc != 0

  - name : Install httpd24-httpd package
    yum:
      name: httpd24-httpd
      state: latest

