---
- name: To fix world writable files
  hosts: all
  become: yes

  tasks:
    - name: Backup of sysctl.conf
      copy:
        src: /etc/sysctl.conf
        dest: /etc/sysctl.conf_{{ ansible_date_time.date }}
        remote_src: yes

    - name: Disable ICMP redirect in sysctl check and run
      sysctl:
        name: "{{ item }}"
        value: 0
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
        - net.ipv4.conf.all.accept_redirects
        - net.ipv4.conf.default.accept_redirects
        - net.ipv4.conf.all.secure_redirects
        - net.ipv4.conf.default.secure_redirects
