---
- name: Install pip for python
  yum:
    name: python27-python-pip
    state: latest

- name: configure path for python from software collection
  copy:
    dest: "/etc/profile.d/python.sh"
    owner: "root"
    group: "root"
    mode: 0644
    content: |
      PATH=$PATH:/opt/rh/python27/root/usr/bin/

- name: configure ldd path for python libries from software collection
  copy:
    dest: "/etc/ld.so.conf.d/python.conf"
    owner: "root"
    group: "root"
    mode: 0644
    content: |
      /opt/rh/python27/root/usr/lib64/

- name: apply ldconfig
  shell: ldconfig

- name: create configure pip.conf to use internal pip repository
  copy:
    dest: "{{ pip_conf_path }}"
    owner: "root"
    group: "root"
    mode: 0644
    content: |
      [global]
      index-url = {{ pip_repo_url }}
      trusted-host = {{ pip_trust_host }}
