- name: To check the home dir permission
  script: files/homedir_permissioncheck_script.sh
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: var_out
- debug: var=var_out.stdout_lines
