- name: Resolving vulnerability of world writable files and folders in system
  include_tasks: world_writable_files_folders.yml
  tags:
    - world_writable

- name: Resolving vulnerability of tcp_timestamps and netfilter
  include_tasks: sysctl_params.yml
  tags:
    - sysctl_params

- name: Resolving vulnerability of ICMP timestamp
  include_tasks: ICMP_timestamps_removal.yml
  tags:
    - ICMP_timestamps
