- name: finding directories with world writable permission excluding sticky bit applied.
  shell: cat /dev/null > /tmp/world_writable_files ; df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \) 2>/dev/null | xargs stat --format '%a %A %u %g %n' | tee -a /tmp/world_writable_files
  register: output_dir
- debug:
    msg: "{{ output_dir.stdout_lines }}"


- name: finding files with world writable permission excluding sticky bit applied.
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f \( -perm -0002 -a ! -perm -1000 \) 2>/dev/null | xargs stat --format '%a %A %u %g %n' | tee -a /tmp/world_writable_files
  register: output_file
- debug:
    msg: "{{ output_file.stdout_lines }}"

- name: Changing the permissions for the directories.
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \) | grep -v histlog 2>/dev/null | xargs chmod o-w
  ignore_errors: yes

- name: Changing the permissions for the files.
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f \( -perm -0002 -a ! -perm -1000 \) | grep -v histlog 2>/dev/null | xargs chmod o-w
  ignore_errors: yes

